// https://api.themoviedb.org/3/search/movie?api_key=9fc6ba08b528d3d577aa1a16484652de&language=en-US&page=1&include_adult=true&query=alien

// https://image.tmdb.org/t/p/w342/zecMELPbU5YMQpC81Z8ImaaXuf9.jpg

export const API = {
    page: 1,
    results: [
        {
            adult: false,
            backdrop_path: '/6jajFcaY2YsfGQstJ5HaqZNVseX.jpg',
            genre_ids: [27, 878, 9648],
            id: 126889,
            original_language: 'en',
            original_title: 'Alien: Covenant',
            overview:
                "Bound for a remote planet on the far side of the galaxy, the crew of the colony ship 'Covenant' discovers what is thought to be an uncharted paradise, but is actually a dark, dangerous world—which has a sole inhabitant: the 'synthetic', David, survivor of the doomed Prometheus expedition.",
            popularity: 141.089,
            poster_path: '/zecMELPbU5YMQpC81Z8ImaaXuf9.jpg',
            release_date: '2017-05-09',
            title: 'Alien: Covenant',
            video: false,
            vote_average: 6,
            vote_count: 6348,
        },
        {
            adult: false,
            backdrop_path: '/sumajFyOoIKubI15POZ0p8Ekpzu.jpg',
            genre_ids: [28, 878, 53],
            id: 593035,
            original_language: 'en',
            original_title: 'Alien Warfare',
            overview:
                'A team of Navy Seals investigates a mysterious science outpost only to have to combat a squad of powerful alien soldiers.',
            popularity: 72.721,
            poster_path: '/rJOj0T5DyChfECevDg0xpEGznsl.jpg',
            release_date: '2019-04-05',
            title: 'Alien Warfare',
            video: false,
            vote_average: 3.9,
            vote_count: 77,
        },
        {
            adult: false,
            backdrop_path: '/AmR3JG1VQVxU8TfAvljUhfSFUOx.jpg',
            genre_ids: [27, 878],
            id: 348,
            original_language: 'en',
            original_title: 'Alien',
            overview:
                'During its return to the earth, commercial spaceship Nostromo intercepts a distress signal from a distant planet. When a three-member team of the crew discovers a chamber containing thousands of eggs on the planet, a creature inside one of the eggs attacks an explorer. The entire crew is unaware of the impending nightmare set to descend upon them when the alien parasite planted inside its unfortunate host is birthed.',
            popularity: 50.045,
            poster_path: '/vfrQk5IPloGg1v9Rzbh2Eg3VGyM.jpg',
            release_date: '1979-05-25',
            title: 'Alien',
            video: false,
            vote_average: 8.1,
            vote_count: 10265,
        },
        {
            adult: false,
            backdrop_path: '/x2lPPe2aH76uyYVhkVCtzTMYawC.jpg',
            genre_ids: [16, 10751, 14],
            id: 656561,
            original_language: 'en',
            original_title: 'Alien Xmas',
            overview:
                "A young elf mistakes a tiny alien for a Christmas gift, not knowing her new plaything has plans to destroy Earth's gravity — and steal all the presents.",
            popularity: 72.378,
            poster_path: '/3UGrAX6D1AMVra80jmUMUOLq8Qr.jpg',
            release_date: '2020-11-20',
            title: 'Alien Xmas',
            video: false,
            vote_average: 6.8,
            vote_count: 84,
        },
        {
            adult: false,
            backdrop_path: '/kwkAGwtwS57FckZq6n44oipW1AN.jpg',
            genre_ids: [878, 27],
            id: 668343,
            original_language: 'en',
            original_title: 'Alien Outbreak',
            overview:
                'In a small rural community, local police officers Zoe and Patrick begin their shift as normal but soon, strange events unfold. Residents begin behaving erratically, and suicidal panic spreads amongst the township they are trying to protect. Zoe and Patrick realise alien machines are taking hold, cutting their small group of survivors off from the outside world. Can the determined humans band together to save their community, and all mankind, from extinction?',
            popularity: 50.297,
            poster_path: '/5m4Gw9wTRxUdDnx7UNn1bNLN54J.jpg',
            release_date: '2020-02-11',
            title: 'Alien Outbreak',
            video: false,
            vote_average: 3.9,
            vote_count: 15,
        },
        {
            adult: false,
            backdrop_path: '/psLgZQDEDfNjNzi1eitG7ubdQL1.jpg',
            genre_ids: [878, 28, 27],
            id: 8077,
            original_language: 'en',
            original_title: 'Alien³',
            overview:
                'After escaping with Newt and Hicks from the alien planet, Ripley crash lands on Fiorina 161, a prison planet and host to a correctional facility. Unfortunately, although Newt and Hicks do not survive the crash, a more unwelcome visitor does. The prison does not allow weapons of any kind, and with aid being a long time away, the prisoners must simply survive in any way they can.',
            popularity: 24.013,
            poster_path: '/hlabk6APJUeihZDaSD9N6iI0f4g.jpg',
            release_date: '1992-05-22',
            title: 'Alien³',
            video: false,
            vote_average: 6.3,
            vote_count: 3832,
        },
        {
            adult: false,
            backdrop_path: '/mXcoOFlpwNepO3TsWGuPb9Aurld.jpg',
            genre_ids: [53, 28, 878],
            id: 312526,
            original_language: 'en',
            original_title: 'Alien Outpost',
            overview:
                'A documentary crew follows an elite unit of soldiers in the wake of an alien invasion.',
            popularity: 32.285,
            poster_path: '/dXe0HXP66DyTv6mw5pxbGq89knr.jpg',
            release_date: '2014-09-19',
            title: 'Alien Outpost',
            video: false,
            vote_average: 4.8,
            vote_count: 128,
        },
        {
            adult: false,
            backdrop_path: '/zQI8yxl61JTpjCB3MrTbcQBOT82.jpg',
            genre_ids: [878, 27, 28],
            id: 8078,
            original_language: 'en',
            original_title: 'Alien Resurrection',
            overview:
                'Two hundred years after Lt. Ripley died, a group of scientists clone her, hoping to breed the ultimate weapon. But the new Ripley is full of surprises … as are the new aliens. Ripley must team with a band of smugglers to keep the creatures from reaching Earth.',
            popularity: 27.837,
            poster_path: '/kzslFL1n01WI5lEcYzFSUi3Quik.jpg',
            release_date: '1997-11-12',
            title: 'Alien Resurrection',
            video: false,
            vote_average: 6.1,
            vote_count: 3299,
        },
        {
            adult: false,
            backdrop_path: '/6BCGb7R4XF1mQsCaJsIel0QgIqo.jpg',
            genre_ids: [27, 878, 53],
            id: 258193,
            original_language: 'en',
            original_title: 'Alien Abduction',
            overview:
                'A vacationing family encounters an alien threat in this pulse-pounding thriller based on the real-life Brown Mountain Lights phenomenon in North Carolina.',
            popularity: 24.196,
            poster_path: '/pe9mSStpQC2doKtYY3VDJdBEBHr.jpg',
            release_date: '2014-04-04',
            title: 'Alien Abduction',
            video: false,
            vote_average: 5.1,
            vote_count: 198,
        },
        {
            adult: false,
            backdrop_path: '/2osX053v71I1Nc0qejnRiU64aMM.jpg',
            genre_ids: [28, 878, 18, 27],
            id: 561859,
            original_language: 'en',
            original_title: 'Alien Overlords',
            overview:
                'A man learns about alien agendas from a dying agent and feels compelled to warn the world about the impending danger.',
            popularity: 29.975,
            poster_path: '/zDtn7lC2ugxWsre4JhdAXA3GTsM.jpg',
            release_date: '2018-11-14',
            title: 'Alien Overlords',
            video: false,
            vote_average: 4.6,
            vote_count: 8,
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [28, 27, 878],
            id: 460962,
            original_language: 'en',
            original_title: 'Alien Convergence',
            overview:
                'When flying reptilian creatures wreak havoc all over the world, the survivors’ only hope of stopping them is a new, state-of-the-art fighter jet piloted by the only team that knows how to use the technology.',
            popularity: 21.363,
            poster_path: '/96xgOCz2li0IiqKYcLQh5bK7CiU.jpg',
            release_date: '2017-06-27',
            title: 'Alien Convergence',
            video: false,
            vote_average: 4.1,
            vote_count: 34,
        },
        {
            adult: false,
            backdrop_path: '/xvq1RLaiwSdHwPHe7WUhqZa1rCA.jpg',
            genre_ids: [12, 878, 28, 27],
            id: 395,
            original_language: 'en',
            original_title: 'AVP: Alien vs. Predator',
            overview:
                'When scientists discover something in the Arctic that appears to be a buried Pyramid, they send a research team out to investigate. Little do they know that they are about to step into a hunting ground where Aliens are grown as sport for the Predator race.',
            popularity: 30.976,
            poster_path: '/2DKoPom57PVtJWcJlq7bS7JpahU.jpg',
            release_date: '2004-08-12',
            title: 'AVP: Alien vs. Predator',
            video: false,
            vote_average: 5.8,
            vote_count: 3012,
        },
        {
            adult: false,
            backdrop_path: '/pZ7PasDyWIafGYTxzzlSWWl6ZgK.jpg',
            genre_ids: [12],
            id: 25642,
            original_language: 'en',
            original_title: 'Ben 10 Alien Swarm',
            overview:
                "Ben tenison is back in this all new Comedy Central, Movie, Based on the current Alien Force story. Alien swarm picks up with Ben 10 as a full fledged plumber but he's about to leave the ranks to do what he believes is right.",
            popularity: 40.019,
            poster_path: '/9D1KSrLM9RnpcKWV7SeNEfDOWIn.jpg',
            release_date: '2009-11-25',
            title: 'Ben 10 Alien Swarm',
            video: false,
            vote_average: 6.4,
            vote_count: 206,
        },
        {
            adult: false,
            backdrop_path: '/h6xShivEaMdlLboH3hLmvaaqKPZ.jpg',
            genre_ids: [27],
            id: 527014,
            original_language: 'en',
            original_title: 'Alien Psychosis',
            overview:
                "Ryan O'Neil, a War Veteran suffering from PTSD after being wounded in combat, returns home to his pregnant wife, Stephanie. Her brother Tony, a corrupt cop, has been helping her out while her husband has been serving the country. Ryan and Tony have never been fond of each other, and things get heated as Tony attempts to meddle with their marriage. But when Ryan starts to have flashes and visions of killers, extraterrestrials, and other strange beings in his house at night, he's not sure whether it is real or if it is just in his mind. Stephanie, already on edge with Ryan, is deeply concerned about her husband's behavior. As the days go by, Ryan will soon find out what sinister presence has been haunting him in his nightmares. (IMDB)",
            popularity: 12.267,
            poster_path: '/zBipFulQKHQTtwv18RKviUap72Z.jpg',
            release_date: '2018-02-24',
            title: 'Alien Psychosis',
            video: false,
            vote_average: 5,
            vote_count: 8,
        },
        {
            adult: false,
            backdrop_path: '/kc20ajqICqsLjvgbfHNnWhDVc85.jpg',
            genre_ids: [28, 878, 12, 27],
            id: 548257,
            original_language: 'en',
            original_title: 'Alien Predator',
            overview:
                'A black ops reconnaissance team is sent to investigate the crash of an unidentified aircraft. When they arrive, they find strange markings and residue visible only in infrared. As the team gets deeper in and tries to figure out the source of the markings, they discover that they are being hunted by an alien expedition to Earth.',
            popularity: 14.076,
            poster_path: '/7SgEtIGBqBtF63H89ZHUsjAVGzX.jpg',
            release_date: '2018-09-11',
            title: 'Alien Predator',
            video: false,
            vote_average: 5,
            vote_count: 21,
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [99, 10770],
            id: 172596,
            original_language: 'en',
            original_title: 'Alien Evolution',
            overview:
                'Mark Kermode brings a tribute to the successful Alien series, featuring interviews with the cast members and directors, including Sigourney Weaver and Ridley Scott.  This documentary is featured on the 9th disc of the Alien Quadrilogy DVD set, released in 2003.',
            popularity: 12.971,
            poster_path: '/bYohwNp2ltWyuRTmNStpg8iGzej.jpg',
            release_date: '2001-10-12',
            title: 'Alien Evolution',
            video: false,
            vote_average: 6,
            vote_count: 16,
        },
        {
            adult: false,
            backdrop_path: '/6zM4bpc42mqYndSRbXHnFTYzwqA.jpg',
            genre_ids: [27, 878, 53],
            id: 13954,
            original_language: 'en',
            original_title: 'Alien Raiders',
            overview:
                "It's the end of yet another night at Hastings Supermarket, a grocery store in Buck Lake, Arizona. But just before closing, a group of masked and armed to the teeth militants invades the store and take everyone hostage",
            popularity: 13.755,
            poster_path: '/gBz8ueJSWIVwB3LO80BiuUFpiWY.jpg',
            release_date: '2008-09-21',
            title: 'Alien Raiders',
            video: false,
            vote_average: 5.2,
            vote_count: 109,
        },
        {
            adult: false,
            backdrop_path: '/hWTqjvMryjtCLMxo90iSqZ89tT4.jpg',
            genre_ids: [878, 28, 12],
            id: 22076,
            original_language: 'en',
            original_title: 'Alien Hunter',
            overview:
                'Government agents find evidence of extraterrestrial life at the South Pole.',
            popularity: 11.823,
            poster_path: '/aNBMcjrncjGd9Yn6TJW3SkQJhMJ.jpg',
            release_date: '2003-07-19',
            title: 'Alien Hunter',
            video: false,
            vote_average: 5.2,
            vote_count: 89,
        },
        {
            adult: false,
            backdrop_path: '/693ku6nEwYC6NYnViEXEro6Hqvx.jpg',
            genre_ids: [99, 9648, 878],
            id: 593230,
            original_language: 'en',
            original_title: 'Alien Messiah',
            overview:
                'Did Aliens influence the Bible? Bold theories are emerging about human prehistory and origins that could turn history as we know it upside down. New research exposes shocking new evidence that the human race was not only engineered by Aliens. but that Jesus was their descendant and the star of Bethlehem was actually a UFO from another world.',
            popularity: 8.595,
            poster_path: '/keIQiVAH3mN9MnVvWxmn6SDyrge.jpg',
            release_date: '2019-03-18',
            title: 'Alien Messiah',
            video: false,
            vote_average: 0,
            vote_count: 0,
        },
        {
            adult: false,
            backdrop_path: null,
            genre_ids: [878, 28, 53],
            id: 104185,
            original_language: 'en',
            original_title: 'Alien Tornado',
            overview:
                'Aliens attack Earth with deadly electrical tornadoes, and it’s up to a farmer, his smart high-school daughter and a tornado blogger to thwart the horrific invasion.',
            popularity: 11.342,
            poster_path: '/bCiOtKLJdYtjie64pO5925OC2vS.jpg',
            release_date: '2012-04-21',
            title: 'Alien Tornado',
            video: false,
            vote_average: 4.3,
            vote_count: 32,
        },
    ],
    total_pages: 35,
    total_results: 697,
}
